### ISSUE TITLE
Tailwind CSS 2 support

### ISSUE THREAD

**Issue by anantakrishna** [benface/tailwindcss-gap#12]
I guess the current version 7.0.0 is not compatible with the latest Tailwind CSS 2.0.1.

I get the following error:

```
TypeError: target is not a function
    at c:\Users\user\source\repos\project\node_modules\tailwindcss-gap\index.js:20:18
    at c:\Users\user\source\repos\project\node_modules\tailwindcss\lib\util\processPlugins.js:69:5
```

**Comment by benface** [comment]
See my comment in #14
